"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostVideoController = exports.createVideo = exports.VideoController = exports.getAllVideosUseCase = void 0;
const CreateVideo_1 = require("../aplication/CreateVideo");
const GetAllVideosUseCase_1 = require("../aplication/GetAllVideosUseCase");
const createVideoController_1 = require("./createVideoController");
const createVideorepository_1 = require("./createVideorepository");
const video_controller_1 = require("./video-controller");
const videoRepository_1 = require("./videoRepository");
const videoRepository = new createVideorepository_1.InMemoryVideoRepository();
const getAllVideosUseCase = new GetAllVideosUseCase_1.GetAllVideos(videoRepository);
exports.getAllVideosUseCase = getAllVideosUseCase;
const VideoController = new video_controller_1.videoController(getAllVideosUseCase);
exports.VideoController = VideoController;
const VideoRepository = new videoRepository_1.AddVideoRepository();
const createVideo = new CreateVideo_1.PostVideos(VideoRepository);
exports.createVideo = createVideo;
const PostVideoController = new createVideoController_1.CreateVideosController(createVideo);
exports.PostVideoController = PostVideoController;
